### PR TITLE
[type:feat] code over issue #44 push assert.go and assert_test.go

### PR DESCRIPTION
**Pull request by yunlongn**

### CODE REVIEW

**Comment by yunlongn** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by yunlongn** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by moremind** [comment]
Please check your local email means `git config user.name "xxx" git config user.email "xxx@gmail.com"`and github email in website.

**Comment by yunlongn** [comment]
I have read the CLA Document and I hereby sign the CLA

**Pull request closed without merging**
